import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import prettier from 'eslint-config-prettier'

/**
 * Linting for the frontend.
 *
 * `prettier` goes last so it switches off every stylistic rule that would
 * argue with the formatter. One tool owns layout, another owns correctness --
 * the same split as ruff format and ruff check on the Python side.
 */
export default [
  // coverage/ is generated by vitest and contains a bundled HTML report.
  { ignores: ['dist/**', 'node_modules/**', 'coverage/**'] },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      globals: { ...globals.browser },
      parserOptions: {
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // A component file that also exports something else breaks fast refresh.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // An unused variable is either a mistake or a leftover; a leading
      // underscore is how you say it is deliberate.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  // Import boundaries between the two applications.
  //
  // A static import by path is the only way owner code can enter the shop's
  // module graph, so this catches the cause at edit time. Written as glob
  // patterns rather than literal relative paths: a page nested one level
  // deeper reaches its sibling tree by '../../' rather than '../', and a
  // literal rule would silently stop matching exactly where a new page is
  // most likely to be added.
  //
  // src/test/ is deliberately unscoped. It is imported only by .test files,
  // which never enter a bundle.
  {
    files: ['src/store/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/owner/**'],
              message:
                'The shop must not import owner code. Move what is shared into src/shared/.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/owner/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/store/**'],
              message:
                'The console must not import shop code. Move what is shared into src/shared/.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['src/shared/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/store/**', '**/owner/**'],
              message:
                'Shared code must not depend on either application; the dependency runs one way.',
            },
          ],
        },
      ],
    },
  },
  prettier,
]
