import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import prettier from 'eslint-config-prettier'

/**
 * Linting for the frontend.
 *
 * `prettier` goes last so it switches off every stylistic rule that would
 * argue with the formatter. One tool owns layout, another owns correctness --
 * the same split as ruff format and ruff check on the Python side.
 */
export default [
  // coverage/ is generated by vitest and contains a bundled HTML report.
  { ignores: ['dist/**', 'node_modules/**', 'coverage/**'] },
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx}'],
    languageOptions: {
      ecmaVersion: 'latest',
      globals: { ...globals.browser },
      parserOptions: {
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // A component file that also exports something else breaks fast refresh.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      // An unused variable is either a mistake or a leftover; a leading
      // underscore is how you say it is deliberate.
      'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  // vite.config.js and the build-time check scripts run under Node, not the
  // browser -- they need `process` and an unrestricted `console`, and never
  // run in a bundle, so react-specific rules do not apply.
  {
    files: ['vite.config.js', 'scripts/**/*.{js,mjs}'],
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      'no-console': 'off',
    },
  },
  // Test files run under vitest's jsdom environment: real `window`/`document`
  // globals, but still inside a genuine Node process, so `process` (e.g. a
  // test that overrides `process.env.TZ` for its own duration) is real too.
  // Neither globals set alone matches what actually exists at runtime here.
  {
    files: ['**/*.test.{js,jsx}', 'src/test/**/*.{js,jsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
  // Import boundaries between the two applications.
  //
  // A static import by path is the only way owner code can enter the shop's
  // module graph, so this catches the cause at edit time. Written as glob
  // patterns rather than literal relative paths: a page nested one level
  // deeper reaches its sibling tree by '../../' rather than '../', and a
  // literal rule would silently stop matching exactly where a new page is
  // most likely to be added.
  //
  // no-restricted-imports only inspects ImportDeclaration /
  // ExportNamedDeclaration source literals, so a dynamic import() --
  // ImportExpression in the AST -- sails past it untouched. That form is a
  // realistic way to reach across the boundary (it's the normal way to
  // code-split a large owner page), and a dynamically imported owner module
  // does land in a chunk the shop can reach, so no-restricted-syntax below
  // covers ImportExpression with the same directory boundary, matched with a
  // regex on the source literal since esquery attribute selectors don't
  // support glob patterns.
  //
  // src/test/ is deliberately unscoped. It is imported only by .test files,
  // which never enter a bundle.
  {
    files: ['src/store/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/owner/**'],
              message:
                'The shop must not import owner code. Move what is shared into src/shared/.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportExpression > Literal[value=/(^|\\/)owner\\//]',
          message:
            'The shop must not import owner code, dynamically either. Move what is shared into src/shared/.',
        },
      ],
    },
  },
  {
    files: ['src/owner/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/store/**'],
              message:
                'The console must not import shop code. Move what is shared into src/shared/.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportExpression > Literal[value=/(^|\\/)store\\//]',
          message:
            'The console must not import shop code, dynamically either. Move what is shared into src/shared/.',
        },
      ],
    },
  },
  {
    files: ['src/shared/**/*.{js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/store/**', '**/owner/**'],
              message:
                'Shared code must not depend on either application; the dependency runs one way.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: 'ImportExpression > Literal[value=/(^|\\/)store\\//]',
          message:
            'Shared code must not depend on either application, dynamically either; the dependency runs one way.',
        },
        {
          selector: 'ImportExpression > Literal[value=/(^|\\/)owner\\//]',
          message:
            'Shared code must not depend on either application, dynamically either; the dependency runs one way.',
        },
      ],
    },
  },
  prettier,
]
