"""add item_field_review

Revision ID: 3f3559d49a9f
Revises: c1a4f0b27e93
Create Date: 2026-09-08 12:27:34.656783

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3f3559d49a9f'
down_revision: str | None = 'c1a4f0b27e93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_field_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'field_name', name='uq_item_field_review')
    )
    op.create_index(op.f('ix_item_field_review_inventory_item_id'), 'item_field_review', ['inventory_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_field_review_inventory_item_id'), table_name='item_field_review')
    op.drop_table('item_field_review')
    # ### end Alembic commands ###
