"""import staging tables

Revision ID: 49f5bc70b58f
Revises: 8fecfabd4f92
Create Date: 2026-09-05 21:16:22.344684

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '49f5bc70b58f'
down_revision: str | None = '8fecfabd4f92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('profile_name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_sha256'), 'import_batch', ['sha256'], unique=False)
    op.create_table('import_row',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('item_kind', sa.String(length=32), nullable=True),
    sa.Column('subtype', sa.String(length=64), nullable=True),
    sa.Column('classified_by_rule', sa.String(length=64), nullable=True),
    sa.Column('inventory_item_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'row_number', name='uq_import_row_batch_number')
    )
    op.create_index(op.f('ix_import_row_batch_id'), 'import_row', ['batch_id'], unique=False)
    op.create_index('ix_import_row_kind', 'import_row', ['item_kind'], unique=False)
    op.create_index('ix_import_row_status', 'import_row', ['status'], unique=False)
    op.create_table('import_issue',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('import_row_id', sa.BigInteger(), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('column_name', sa.String(length=64), nullable=True),
    sa.Column('raw_value', sa.String(length=512), nullable=True),
    sa.Column('proposed', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['import_row_id'], ['import_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_issue_import_row_id'), 'import_issue', ['import_row_id'], unique=False)
    op.create_index('ix_import_issue_raw_value', 'import_issue', ['raw_value'], unique=False)
    op.create_index('ix_import_issue_rule', 'import_issue', ['rule'], unique=False)
    op.create_index('ix_import_issue_severity', 'import_issue', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_import_issue_severity', table_name='import_issue')
    op.drop_index('ix_import_issue_rule', table_name='import_issue')
    op.drop_index('ix_import_issue_raw_value', table_name='import_issue')
    op.drop_index(op.f('ix_import_issue_import_row_id'), table_name='import_issue')
    op.drop_table('import_issue')
    op.drop_index('ix_import_row_status', table_name='import_row')
    op.drop_index('ix_import_row_kind', table_name='import_row')
    op.drop_index(op.f('ix_import_row_batch_id'), table_name='import_row')
    op.drop_table('import_row')
    op.drop_index(op.f('ix_import_batch_sha256'), table_name='import_batch')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
