"""link staging rows to inventory items

Revision ID: 52d8e576815a
Revises: 7c3922fb3a9e
Create Date: 2026-09-06 13:55:57.023764

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '52d8e576815a'
down_revision: str | None = '7c3922fb3a9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_row', 'inventory_item_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_import_row_inventory_item_id'), 'import_row', ['inventory_item_id'], unique=False)
    # Named explicitly: an anonymous constraint cannot be dropped by the
    # downgrade, which fails with "it has no name".
    op.create_foreign_key(
        'fk_import_row_inventory_item', 'import_row', 'inventory_item',
        ['inventory_item_id'], ['id'], ondelete='SET NULL',
    )
    op.drop_index(op.f('ix_inventory_item_fts'), table_name='inventory_item', postgresql_using='gin')
    op.create_index('ix_inventory_item_fts', 'inventory_item', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_item_fts', table_name='inventory_item', postgresql_using='gin')
    op.create_index(op.f('ix_inventory_item_fts'), 'inventory_item', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || description)")], unique=False, postgresql_using='gin')
    op.drop_constraint('fk_import_row_inventory_item', 'import_row', type_='foreignkey')
    op.drop_index(op.f('ix_import_row_inventory_item_id'), table_name='import_row')
    op.alter_column('import_row', 'inventory_item_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
