"""optimistic concurrency version columns

Revision ID: 5c6585b1eadf
Revises: 600582ecc973
Create Date: 2026-09-06 19:40:17.339198

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5c6585b1eadf'
down_revision: str | None = '600582ecc973'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('listing', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'version')
    op.drop_column('inventory_item', 'version')
    # ### end Alembic commands ###
