"""partial indexes for search facets

Revision ID: 600582ecc973
Revises: fdf22151d022
Create Date: 2026-09-06 19:26:36.407777

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '600582ecc973'
down_revision: str | None = 'fdf22151d022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_inventory_item_facet_bullion', 'inventory_item', ['bullion_form_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_country', 'inventory_item', ['country_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_disposition', 'inventory_item', ['disposition_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_grade', 'inventory_item', ['grade_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_kind', 'inventory_item', ['item_kind_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_metal', 'inventory_item', ['metal_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    op.create_index('ix_inventory_item_facet_status', 'inventory_item', ['status_id'], unique=False, postgresql_where=sa.text('split_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_item_facet_status', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_metal', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_kind', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_grade', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_disposition', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_country', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    op.drop_index('ix_inventory_item_facet_bullion', table_name='inventory_item', postgresql_where=sa.text('split_at IS NULL'))
    # ### end Alembic commands ###
