"""target schema

Revision ID: 7c3922fb3a9e
Revises: 49f5bc70b58f
Create Date: 2026-09-06 13:49:32.473042

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models.views import CREATE_VIEWS_ORIGINAL, DROP_VIEWS
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7c3922fb3a9e'
down_revision: str | None = '49f5bc70b58f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The scaffold's PostgreSQL enum type was called `item_kind`, and the
    # target schema has a reference *table* of that name. In PostgreSQL a
    # table implicitly creates a composite type, so tables and types share one
    # namespace and the two genuinely collide.
    #
    # This must run before any CREATE TABLE below. Renaming the type also
    # retypes `coins.kind` in place, which is why autogenerate's ALTER COLUMN
    # for that column was removed rather than kept.
    op.execute("ALTER TYPE item_kind RENAME TO coin_kind")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authenticity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_authenticity_code')
    )
    op.create_table('carrier',
    sa.Column('tracking_url_template', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_carrier_code')
    )
    op.create_table('country',
    sa.Column('iso_alpha2', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_country_code')
    )
    op.create_table('currency',
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('minor_units', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_currency_code')
    )
    op.create_table('disposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_disposition_code')
    )
    op.create_table('error_type',
    sa.Column('applies_to', sa.Enum('coin', 'currency', 'any', name='applies_to'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_error_type_code')
    )
    op.create_index(op.f('ix_error_type_applies_to'), 'error_type', ['applies_to'], unique=False)
    op.create_table('fed_district',
    sa.Column('letter', sa.String(length=1), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_fed_district_code')
    )
    op.create_table('grade_designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_grade_designation_code')
    )
    op.create_table('grade_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_grade_scale_code')
    )
    op.create_table('grading_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_grading_service_code')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_ref', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name='ck_image_byte_size_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_image_sha256')
    )
    op.create_index(op.f('ix_image_captured_at'), 'image', ['captured_at'], unique=False)
    op.create_table('image_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_image_role_code')
    )
    op.create_table('item_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_item_kind_code')
    )
    op.create_table('item_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_item_status_code')
    )
    op.create_table('metal',
    sa.Column('symbol', sa.String(length=4), nullable=False),
    sa.Column('is_precious', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_metal_code')
    )
    op.create_table('note_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_note_attribute_code')
    )
    op.create_table('note_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_note_type_code')
    )
    op.create_table('sales_order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_sales_order_status_code')
    )
    op.create_table('seal_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_seal_color_code')
    )
    op.create_table('set_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_set_form_code')
    )
    op.create_table('shipment_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_shipment_status_code')
    )
    op.create_table('signature_combination',
    sa.Column('treasurer', sa.String(length=128), nullable=False),
    sa.Column('secretary', sa.String(length=128), nullable=False),
    sa.Column('term_from', sa.Integer(), nullable=True),
    sa.Column('term_to', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_signature_combination_code')
    )
    op.create_table('storage_form',
    sa.Column('default_quantity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_storage_form_code')
    )
    op.create_table('storage_location_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_storage_location_kind_code')
    )
    op.create_table('valuation_basis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_valuation_basis_code')
    )
    op.create_table('vendor_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_vendor_kind_code')
    )
    op.create_table('bullion_form',
    sa.Column('metal_id', sa.Integer(), nullable=True),
    sa.Column('typical_fine_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('typical_fineness', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_bullion_form_code')
    )
    op.create_index(op.f('ix_bullion_form_metal_id'), 'bullion_form', ['metal_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_customer_user')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_table('denomination',
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('kind', sa.Enum('coin', 'note', name='denomination_kind'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_denomination_code'),
    sa.UniqueConstraint('currency_id', 'face_value', 'kind', name='uq_denomination_value')
    )
    op.create_index(op.f('ix_denomination_currency_id'), 'denomination', ['currency_id'], unique=False)
    op.create_table('grade',
    sa.Column('grade_scale_id', sa.Integer(), nullable=True),
    sa.Column('numeric_value', sa.Integer(), nullable=True),
    sa.Column('is_proof', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.ForeignKeyConstraint(['grade_scale_id'], ['grade_scale.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_grade_code')
    )
    op.create_index(op.f('ix_grade_grade_scale_id'), 'grade', ['grade_scale_id'], unique=False)
    op.create_table('image_derivative',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('thumb', 'web', name='derivative_kind'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id', 'kind', name='uq_image_derivative_kind')
    )
    op.create_index(op.f('ix_image_derivative_image_id'), 'image_derivative', ['image_id'], unique=False)
    op.create_table('metal_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal_id', sa.Integer(), nullable=False),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_ozt', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(length=64), server_default=sa.text("'manual'"), nullable=False),
    sa.CheckConstraint('price_per_ozt >= 0', name='ck_metal_price_non_negative'),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_id', 'quoted_at', name='uq_metal_price_quote')
    )
    op.create_index('ix_metal_price_latest', 'metal_price', ['metal_id', sa.literal_column('quoted_at DESC')], unique=False)
    op.create_table('mint',
    sa.Column('mark', sa.String(length=4), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_mint_code')
    )
    op.create_index(op.f('ix_mint_country_id'), 'mint', ['country_id'], unique=False)
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_location_kind_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('identifier', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storage_location_kind_id'], ['storage_location_kind.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_location_kind_id', 'institution', 'identifier', name='uq_storage_location_identity')
    )
    op.create_index(op.f('ix_storage_location_storage_location_kind_id'), 'storage_location', ['storage_location_kind_id'], unique=False)
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('vendor_kind_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_kind_id'], ['vendor_kind.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vendor_name')
    )
    op.create_index(op.f('ix_vendor_host'), 'vendor', ['host'], unique=False)
    op.create_index(op.f('ix_vendor_vendor_kind_id'), 'vendor', ['vendor_kind_id'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_kind', sa.Enum('shipping', 'billing', name='address_kind'), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=False),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from', name='ck_address_validity_range'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_customer_id'), 'address', ['customer_id'], unique=False)
    op.create_index('uq_address_default', 'address', ['customer_id', 'address_kind'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('year_from', sa.Integer(), nullable=False),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('metal_id', sa.Integer(), nullable=False),
    sa.Column('fineness', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('gross_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fine_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fine_weight_ozt >= 0', name='ck_composition_fine_weight_non_negative'),
    sa.CheckConstraint('fineness > 0 AND fineness <= 1', name='ck_composition_fineness_fraction'),
    sa.CheckConstraint('year_to IS NULL OR year_to >= year_from', name='ck_composition_year_range'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('denomination_id', 'country_id', 'year_from', 'metal_id', name='uq_composition_span')
    )
    op.create_index(op.f('ix_composition_country_id'), 'composition', ['country_id'], unique=False)
    op.create_index(op.f('ix_composition_denomination_id'), 'composition', ['denomination_id'], unique=False)
    op.create_index('ix_composition_lookup', 'composition', ['denomination_id', 'country_id', 'year_from'], unique=False)
    op.create_index(op.f('ix_composition_metal_id'), 'composition', ['metal_id'], unique=False)
    op.create_table('friedberg_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fr_number', sa.String(length=32), nullable=False),
    sa.Column('base_number', sa.Integer(), nullable=True),
    sa.Column('district_letter', sa.String(length=1), nullable=True),
    sa.Column('note_type_id', sa.Integer(), nullable=True),
    sa.Column('denomination_id', sa.Integer(), nullable=True),
    sa.Column('series_year', sa.Integer(), nullable=True),
    sa.Column('series_letter', sa.String(length=4), nullable=True),
    sa.Column('seal_color_id', sa.Integer(), nullable=True),
    sa.Column('signature_combination_id', sa.Integer(), nullable=True),
    sa.Column('size_class', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("size_class IS NULL OR size_class IN ('large', 'small', 'fractional')", name='ck_friedberg_number_size_class'),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seal_color_id'], ['seal_color.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signature_combination_id'], ['signature_combination.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fr_number', name='uq_friedberg_number_fr_number')
    )
    op.create_index(op.f('ix_friedberg_number_base_number'), 'friedberg_number', ['base_number'], unique=False)
    op.create_index(op.f('ix_friedberg_number_denomination_id'), 'friedberg_number', ['denomination_id'], unique=False)
    op.create_index(op.f('ix_friedberg_number_note_type_id'), 'friedberg_number', ['note_type_id'], unique=False)
    op.create_index(op.f('ix_friedberg_number_seal_color_id'), 'friedberg_number', ['seal_color_id'], unique=False)
    op.create_index(op.f('ix_friedberg_number_series_year'), 'friedberg_number', ['series_year'], unique=False)
    op.create_index(op.f('ix_friedberg_number_signature_combination_id'), 'friedberg_number', ['signature_combination_id'], unique=False)
    op.create_index('uq_friedberg_number_identity', 'friedberg_number', ['denomination_id', 'series_year', 'series_letter', 'note_type_id', 'district_letter'], unique=True, postgresql_where=sa.text('denomination_id IS NOT NULL AND series_year IS NOT NULL AND note_type_id IS NOT NULL'))
    op.create_table('pcgs_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pcgs_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('denomination_id', sa.Integer(), nullable=True),
    sa.Column('series', sa.String(length=128), nullable=True),
    sa.Column('variety', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mint_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mint_id'], ['mint.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pcgs_number', name='uq_pcgs_type_number')
    )
    op.create_index(op.f('ix_pcgs_type_denomination_id'), 'pcgs_type', ['denomination_id'], unique=False)
    op.create_index(op.f('ix_pcgs_type_mint_id'), 'pcgs_type', ['mint_id'], unique=False)
    op.create_index(op.f('ix_pcgs_type_series'), 'pcgs_type', ['series'], unique=False)
    op.create_index(op.f('ix_pcgs_type_year'), 'pcgs_type', ['year'], unique=False)
    op.create_index('uq_pcgs_type_identity', 'pcgs_type', ['denomination_id', 'year', 'mint_id', 'variety'], unique=True, postgresql_where=sa.text('denomination_id IS NOT NULL AND year IS NOT NULL AND mint_id IS NOT NULL'))
    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=128), nullable=True),
    sa.Column('ordered_on', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_ordered_on'), 'purchase_order', ['ordered_on'], unique=False)
    op.create_index(op.f('ix_purchase_order_vendor_id'), 'purchase_order', ['vendor_id'], unique=False)
    op.create_index('uq_purchase_order_vendor_number', 'purchase_order', ['vendor_id', 'order_number'], unique=True, postgresql_where=sa.text('order_number IS NOT NULL'))
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('item_kind_id', sa.Integer(), nullable=False),
    sa.Column('denomination_id', sa.Integer(), nullable=True),
    sa.Column('bullion_form_id', sa.Integer(), nullable=True),
    sa.Column('set_form_id', sa.Integer(), nullable=True),
    sa.Column('storage_form_id', sa.Integer(), nullable=False),
    sa.Column('storage_quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('grade_id', sa.Integer(), nullable=True),
    sa.Column('grade_designation_id', sa.Integer(), nullable=True),
    sa.Column('grading_service_id', sa.Integer(), nullable=True),
    sa.Column('authenticity_id', sa.Integer(), nullable=False),
    sa.Column('error_type_id', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('disposition_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('local_catalog_number', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('listing_url', sa.String(length=1000), nullable=True),
    sa.Column('notes_raw', sa.Text(), nullable=True),
    sa.Column('denom_raw', sa.Text(), nullable=True),
    sa.Column('year_raw', sa.Text(), nullable=True),
    sa.Column('grade_raw', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=6, scale=4), server_default=sa.text('0.0635'), nullable=False),
    sa.Column('taxes', sa.Numeric(precision=12, scale=2), sa.Computed('round((price + shipping) * tax_rate, 2)', persisted=True), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), sa.Computed('price + shipping + round((price + shipping) * tax_rate, 2)', persisted=True), nullable=False),
    sa.Column('numismatic_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valuation_basis_id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=True),
    sa.Column('metal_id', sa.Integer(), nullable=True),
    sa.Column('fineness', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('gross_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('fine_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('weight_raw', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source', sa.Enum('seeded', 'derived', 'manual', name='provenance_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fine_weight_ozt IS NULL OR fine_weight_ozt >= 0', name='ck_inventory_item_fine_weight_non_negative'),
    sa.CheckConstraint('fine_weight_ozt IS NULL OR gross_weight_ozt IS NULL OR fine_weight_ozt <= gross_weight_ozt', name='ck_inventory_item_fine_within_gross'),
    sa.CheckConstraint('fineness IS NULL OR (fineness > 0 AND fineness <= 1)', name='ck_inventory_item_fineness_fraction'),
    sa.CheckConstraint('gross_weight_ozt IS NULL OR gross_weight_ozt >= 0', name='ck_inventory_item_gross_weight_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_inventory_item_price_non_negative'),
    sa.CheckConstraint('shipping >= 0', name='ck_inventory_item_shipping_non_negative'),
    sa.CheckConstraint('storage_quantity > 0', name='ck_inventory_item_quantity_positive'),
    sa.CheckConstraint('year_end IS NULL OR year_start IS NULL OR year_end >= year_start', name='ck_inventory_item_year_range'),
    sa.ForeignKeyConstraint(['authenticity_id'], ['authenticity.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bullion_form_id'], ['bullion_form.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['denomination_id'], ['denomination.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disposition_id'], ['disposition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['error_type_id'], ['error_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_designation_id'], ['grade_designation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grading_service_id'], ['grading_service.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_kind_id'], ['item_kind.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metal_id'], ['metal.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_form_id'], ['set_form.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['item_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_form_id'], ['storage_form.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['valuation_basis_id'], ['valuation_basis.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_item_attributes', 'inventory_item', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inventory_item_authenticity_id'), 'inventory_item', ['authenticity_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_bullion_form_id'), 'inventory_item', ['bullion_form_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_composition_id'), 'inventory_item', ['composition_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_country_id'), 'inventory_item', ['country_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_denomination_id'), 'inventory_item', ['denomination_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_disposition_id'), 'inventory_item', ['disposition_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_error_type_id'), 'inventory_item', ['error_type_id'], unique=False)
    op.create_index('ix_inventory_item_fts', 'inventory_item', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_inventory_item_grade_designation_id'), 'inventory_item', ['grade_designation_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_grade_id'), 'inventory_item', ['grade_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_grading_service_id'), 'inventory_item', ['grading_service_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_item_kind_id'), 'inventory_item', ['item_kind_id'], unique=False)
    op.create_index('ix_inventory_item_kind_status', 'inventory_item', ['item_kind_id', 'status_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_local_catalog_number'), 'inventory_item', ['local_catalog_number'], unique=False)
    op.create_index(op.f('ix_inventory_item_metal_id'), 'inventory_item', ['metal_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_purchase_order_id'), 'inventory_item', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_set_form_id'), 'inventory_item', ['set_form_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_status_id'), 'inventory_item', ['status_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_storage_form_id'), 'inventory_item', ['storage_form_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_storage_location_id'), 'inventory_item', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_valuation_basis_id'), 'inventory_item', ['valuation_basis_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_year_start'), 'inventory_item', ['year_start'], unique=False)
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_order_status_id', sa.Integer(), nullable=False),
    sa.Column('shipping_address_id', sa.Integer(), nullable=True),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_amount >= 0', name='ck_sales_order_total_non_negative'),
    sa.ForeignKeyConstraint(['billing_address_id'], ['address.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_status_id'], ['sales_order_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['address.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_customer_id'), 'sales_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_order_placed_at'), 'sales_order', ['placed_at'], unique=False)
    op.create_index(op.f('ix_sales_order_sales_order_status_id'), 'sales_order', ['sales_order_status_id'], unique=False)
    op.create_table('coin_detail',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('mint_id', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=128), nullable=True),
    sa.Column('pcgs_type_id', sa.Integer(), nullable=True),
    sa.Column('pcgs_status', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.CheckConstraint("pcgs_status IN ('unknown', 'proposed', 'confirmed', 'conflicting')", name='ck_coin_detail_pcgs_status'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mint_id'], ['mint.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pcgs_type_id'], ['pcgs_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_coin_detail_mint_id'), 'coin_detail', ['mint_id'], unique=False)
    op.create_index(op.f('ix_coin_detail_pcgs_type_id'), 'coin_detail', ['pcgs_type_id'], unique=False)
    op.create_table('currency_detail',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('note_type_id', sa.Integer(), nullable=True),
    sa.Column('series_year', sa.Integer(), nullable=True),
    sa.Column('series_letter', sa.String(length=4), nullable=True),
    sa.Column('seal_color_id', sa.Integer(), nullable=True),
    sa.Column('signature_combination_id', sa.Integer(), nullable=True),
    sa.Column('fed_district_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('friedberg_id', sa.Integer(), nullable=True),
    sa.Column('friedberg_status', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.CheckConstraint("friedberg_status IN ('unknown', 'proposed', 'confirmed', 'conflicting')", name='ck_currency_detail_friedberg_status'),
    sa.ForeignKeyConstraint(['fed_district_id'], ['fed_district.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['friedberg_id'], ['friedberg_number.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_type.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seal_color_id'], ['seal_color.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signature_combination_id'], ['signature_combination.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_item_id')
    )
    op.create_index(op.f('ix_currency_detail_fed_district_id'), 'currency_detail', ['fed_district_id'], unique=False)
    op.create_index(op.f('ix_currency_detail_friedberg_id'), 'currency_detail', ['friedberg_id'], unique=False)
    op.create_index(op.f('ix_currency_detail_note_type_id'), 'currency_detail', ['note_type_id'], unique=False)
    op.create_index(op.f('ix_currency_detail_seal_color_id'), 'currency_detail', ['seal_color_id'], unique=False)
    op.create_index(op.f('ix_currency_detail_serial_number'), 'currency_detail', ['serial_number'], unique=False)
    op.create_index(op.f('ix_currency_detail_signature_combination_id'), 'currency_detail', ['signature_combination_id'], unique=False)
    op.create_table('item_certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('grading_service_id', sa.Integer(), nullable=True),
    sa.Column('cert_number', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grading_service_id'], ['grading_service.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_certification_cert_number'), 'item_certification', ['cert_number'], unique=False)
    op.create_index(op.f('ix_item_certification_grading_service_id'), 'item_certification', ['grading_service_id'], unique=False)
    op.create_index(op.f('ix_item_certification_inventory_item_id'), 'item_certification', ['inventory_item_id'], unique=False)
    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('image_role_id', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_role_id'], ['image_role.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_item_id', 'image_id', name='uq_item_image_pair')
    )
    op.create_index(op.f('ix_item_image_image_id'), 'item_image', ['image_id'], unique=False)
    op.create_index(op.f('ix_item_image_image_role_id'), 'item_image', ['image_role_id'], unique=False)
    op.create_index(op.f('ix_item_image_inventory_item_id'), 'item_image', ['inventory_item_id'], unique=False)
    op.create_index('uq_item_image_primary', 'item_image', ['inventory_item_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('item_note_attribute',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('note_attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_attribute_id'], ['note_attribute.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('inventory_item_id', 'note_attribute_id')
    )
    op.create_table('item_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('from_status_id', sa.Integer(), nullable=True),
    sa.Column('to_status_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_status_id'], ['item_status.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_status_id'], ['item_status.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_status_history_inventory_item_id'), 'item_status_history', ['inventory_item_id'], unique=False)
    op.create_index('ix_item_status_history_item_time', 'item_status_history', ['inventory_item_id', sa.literal_column('changed_at DESC')], unique=False)
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('title', sa.String(length=500), server_default=sa.text("''"), nullable=False),
    sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_listing_price_non_negative'),
    sa.CheckConstraint('quantity_available >= 0', name='ck_listing_quantity_non_negative'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_active', 'listing', ['inventory_item_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index(op.f('ix_listing_inventory_item_id'), 'listing', ['inventory_item_id'], unique=False)
    op.create_table('location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moved_by_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_inventory_item_id'), 'location_history', ['inventory_item_id'], unique=False)
    op.create_index('ix_location_history_item_time', 'location_history', ['inventory_item_id', sa.literal_column('moved_at DESC')], unique=False)
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('shipment_status_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('service_level', sa.String(length=64), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('insured_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('weight_oz', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost IS NULL OR cost >= 0', name='ck_shipment_cost'),
    sa.CheckConstraint('insured_value IS NULL OR insured_value >= 0', name='ck_shipment_insured_value'),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_status_id'], ['shipment_status.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_carrier_id'), 'shipment', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_shipment_sales_order_id'), 'shipment', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_shipment_shipment_status_id'), 'shipment', ['shipment_status_id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_number'), 'shipment', ['tracking_number'], unique=False)
    op.create_table('valuation_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valuation_basis_id', sa.Integer(), nullable=False),
    sa.Column('spot_price_used', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fine_weight_ozt', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('storage_quantity', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('melt_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('numismatic_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reported_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['valuation_basis_id'], ['valuation_basis.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuation_snapshot_inventory_item_id'), 'valuation_snapshot', ['inventory_item_id'], unique=False)
    op.create_index('ix_valuation_snapshot_item_time', 'valuation_snapshot', ['inventory_item_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('listing_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'image_id', name='uq_listing_image_pair')
    )
    op.create_index(op.f('ix_listing_image_image_id'), 'listing_image', ['image_id'], unique=False)
    op.create_index(op.f('ix_listing_image_listing_id'), 'listing_image', ['listing_id'], unique=False)
    op.create_table('sales_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_order_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_sales_order_item_price_non_negative'),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_item_listing_id'), 'sales_order_item', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sales_order_item_sales_order_id'), 'sales_order_item', ['sales_order_id'], unique=False)
    op.create_table('shipment_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('packed', 'label', 'handover', 'damage', name='shipment_image_kind'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'image_id', 'kind', name='uq_shipment_image_pair')
    )
    op.create_index(op.f('ix_shipment_image_image_id'), 'shipment_image', ['image_id'], unique=False)
    op.create_index(op.f('ix_shipment_image_shipment_id'), 'shipment_image', ['shipment_id'], unique=False)
    # ### end Alembic commands ###

    # Views are not in Base.metadata -- autogenerate reflects tables only --
    # so the migration that creates the tables they read owns them too.
    #
    # The ORIGINAL definitions, not the current ones: later revisions add
    # columns these views now select, and a fresh `upgrade head` would fail
    # here on a column that does not exist yet.
    for statement in CREATE_VIEWS_ORIGINAL:
        op.execute(statement)


def downgrade() -> None:
    # Views depend on the tables below, so they go first.
    for statement in DROP_VIEWS:
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_image_shipment_id'), table_name='shipment_image')
    op.drop_index(op.f('ix_shipment_image_image_id'), table_name='shipment_image')
    op.drop_table('shipment_image')
    op.drop_index(op.f('ix_sales_order_item_sales_order_id'), table_name='sales_order_item')
    op.drop_index(op.f('ix_sales_order_item_listing_id'), table_name='sales_order_item')
    op.drop_table('sales_order_item')
    op.drop_index(op.f('ix_listing_image_listing_id'), table_name='listing_image')
    op.drop_index(op.f('ix_listing_image_image_id'), table_name='listing_image')
    op.drop_table('listing_image')
    op.drop_index('ix_valuation_snapshot_item_time', table_name='valuation_snapshot')
    op.drop_index(op.f('ix_valuation_snapshot_inventory_item_id'), table_name='valuation_snapshot')
    op.drop_table('valuation_snapshot')
    op.drop_index(op.f('ix_shipment_tracking_number'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_shipment_status_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_sales_order_id'), table_name='shipment')
    op.drop_index(op.f('ix_shipment_carrier_id'), table_name='shipment')
    op.drop_table('shipment')
    op.drop_index('ix_location_history_item_time', table_name='location_history')
    op.drop_index(op.f('ix_location_history_inventory_item_id'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_index(op.f('ix_listing_inventory_item_id'), table_name='listing')
    op.drop_index('ix_listing_active', table_name='listing', postgresql_where=sa.text('is_active'))
    op.drop_table('listing')
    op.drop_index('ix_item_status_history_item_time', table_name='item_status_history')
    op.drop_index(op.f('ix_item_status_history_inventory_item_id'), table_name='item_status_history')
    op.drop_table('item_status_history')
    op.drop_table('item_note_attribute')
    op.drop_index('uq_item_image_primary', table_name='item_image', postgresql_where=sa.text('is_primary'))
    op.drop_index(op.f('ix_item_image_inventory_item_id'), table_name='item_image')
    op.drop_index(op.f('ix_item_image_image_role_id'), table_name='item_image')
    op.drop_index(op.f('ix_item_image_image_id'), table_name='item_image')
    op.drop_table('item_image')
    op.drop_index(op.f('ix_item_certification_inventory_item_id'), table_name='item_certification')
    op.drop_index(op.f('ix_item_certification_grading_service_id'), table_name='item_certification')
    op.drop_index(op.f('ix_item_certification_cert_number'), table_name='item_certification')
    op.drop_table('item_certification')
    op.drop_index(op.f('ix_currency_detail_signature_combination_id'), table_name='currency_detail')
    op.drop_index(op.f('ix_currency_detail_serial_number'), table_name='currency_detail')
    op.drop_index(op.f('ix_currency_detail_seal_color_id'), table_name='currency_detail')
    op.drop_index(op.f('ix_currency_detail_note_type_id'), table_name='currency_detail')
    op.drop_index(op.f('ix_currency_detail_friedberg_id'), table_name='currency_detail')
    op.drop_index(op.f('ix_currency_detail_fed_district_id'), table_name='currency_detail')
    op.drop_table('currency_detail')
    op.drop_index(op.f('ix_coin_detail_pcgs_type_id'), table_name='coin_detail')
    op.drop_index(op.f('ix_coin_detail_mint_id'), table_name='coin_detail')
    op.drop_table('coin_detail')
    op.drop_index(op.f('ix_sales_order_sales_order_status_id'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_placed_at'), table_name='sales_order')
    op.drop_index(op.f('ix_sales_order_customer_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_index(op.f('ix_inventory_item_year_start'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_valuation_basis_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_storage_location_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_storage_form_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_status_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_set_form_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_purchase_order_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_metal_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_local_catalog_number'), table_name='inventory_item')
    op.drop_index('ix_inventory_item_kind_status', table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_item_kind_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_grading_service_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_grade_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_grade_designation_id'), table_name='inventory_item')
    op.drop_index('ix_inventory_item_fts', table_name='inventory_item', postgresql_using='gin')
    op.drop_index(op.f('ix_inventory_item_error_type_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_disposition_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_denomination_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_country_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_composition_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_bullion_form_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_authenticity_id'), table_name='inventory_item')
    op.drop_index('ix_inventory_item_attributes', table_name='inventory_item', postgresql_using='gin')
    op.drop_table('inventory_item')
    op.drop_index('uq_purchase_order_vendor_number', table_name='purchase_order', postgresql_where=sa.text('order_number IS NOT NULL'))
    op.drop_index(op.f('ix_purchase_order_vendor_id'), table_name='purchase_order')
    op.drop_index(op.f('ix_purchase_order_ordered_on'), table_name='purchase_order')
    op.drop_table('purchase_order')
    op.drop_index('uq_pcgs_type_identity', table_name='pcgs_type', postgresql_where=sa.text('denomination_id IS NOT NULL AND year IS NOT NULL AND mint_id IS NOT NULL'))
    op.drop_index(op.f('ix_pcgs_type_year'), table_name='pcgs_type')
    op.drop_index(op.f('ix_pcgs_type_series'), table_name='pcgs_type')
    op.drop_index(op.f('ix_pcgs_type_mint_id'), table_name='pcgs_type')
    op.drop_index(op.f('ix_pcgs_type_denomination_id'), table_name='pcgs_type')
    op.drop_table('pcgs_type')
    op.drop_index('uq_friedberg_number_identity', table_name='friedberg_number', postgresql_where=sa.text('denomination_id IS NOT NULL AND series_year IS NOT NULL AND note_type_id IS NOT NULL'))
    op.drop_index(op.f('ix_friedberg_number_signature_combination_id'), table_name='friedberg_number')
    op.drop_index(op.f('ix_friedberg_number_series_year'), table_name='friedberg_number')
    op.drop_index(op.f('ix_friedberg_number_seal_color_id'), table_name='friedberg_number')
    op.drop_index(op.f('ix_friedberg_number_note_type_id'), table_name='friedberg_number')
    op.drop_index(op.f('ix_friedberg_number_denomination_id'), table_name='friedberg_number')
    op.drop_index(op.f('ix_friedberg_number_base_number'), table_name='friedberg_number')
    op.drop_table('friedberg_number')
    op.drop_index(op.f('ix_composition_metal_id'), table_name='composition')
    op.drop_index('ix_composition_lookup', table_name='composition')
    op.drop_index(op.f('ix_composition_denomination_id'), table_name='composition')
    op.drop_index(op.f('ix_composition_country_id'), table_name='composition')
    op.drop_table('composition')
    op.drop_index('uq_address_default', table_name='address', postgresql_where=sa.text('is_default'))
    op.drop_index(op.f('ix_address_customer_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_vendor_vendor_kind_id'), table_name='vendor')
    op.drop_index(op.f('ix_vendor_host'), table_name='vendor')
    op.drop_table('vendor')
    op.drop_index(op.f('ix_storage_location_storage_location_kind_id'), table_name='storage_location')
    op.drop_table('storage_location')
    op.drop_index(op.f('ix_mint_country_id'), table_name='mint')
    op.drop_table('mint')
    op.drop_index('ix_metal_price_latest', table_name='metal_price')
    op.drop_table('metal_price')
    op.drop_index(op.f('ix_image_derivative_image_id'), table_name='image_derivative')
    op.drop_table('image_derivative')
    op.drop_index(op.f('ix_grade_grade_scale_id'), table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_denomination_currency_id'), table_name='denomination')
    op.drop_table('denomination')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_bullion_form_metal_id'), table_name='bullion_form')
    op.drop_table('bullion_form')
    op.drop_table('vendor_kind')
    op.drop_table('valuation_basis')
    op.drop_table('storage_location_kind')
    op.drop_table('storage_form')
    op.drop_table('signature_combination')
    op.drop_table('shipment_status')
    op.drop_table('set_form')
    op.drop_table('seal_color')
    op.drop_table('sales_order_status')
    op.drop_table('note_type')
    op.drop_table('note_attribute')
    op.drop_table('metal')
    op.drop_table('item_status')
    op.drop_table('item_kind')
    op.drop_table('image_role')
    op.drop_index(op.f('ix_image_captured_at'), table_name='image')
    op.drop_table('image')
    op.drop_table('grading_service')
    op.drop_table('grade_scale')
    op.drop_table('grade_designation')
    op.drop_table('fed_district')
    op.drop_index(op.f('ix_error_type_applies_to'), table_name='error_type')
    op.drop_table('error_type')
    op.drop_table('disposition')
    op.drop_table('currency')
    op.drop_table('country')
    op.drop_table('carrier')
    op.drop_table('authenticity')
    # ### end Alembic commands ###

    # Alembic drops tables on downgrade but never the enum TYPES it created,
    # so without this a downgrade followed by an upgrade fails on
    # "type provenance_source already exists". Dropping them is safe only
    # after every table using them is gone, which is the case here.
    for enum_name in (
        "provenance_source",
        "denomination_kind",
        "applies_to",
        "derivative_kind",
        "shipment_image_kind",
        "address_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # The type rename is undone last: the `item_kind` table that collided
    # with it has been dropped by this point.
    op.execute("ALTER TYPE coin_kind RENAME TO item_kind")
