"""add plate numbers to currency_detail

Revision ID: 9cc26d4f74b5
Revises: bec2c77439cc
Create Date: 2026-09-10 12:01:56.917867

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9cc26d4f74b5'
down_revision: str | None = 'bec2c77439cc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_detail', sa.Column('face_plate_number', sa.String(length=16), nullable=True))
    op.add_column('currency_detail', sa.Column('back_plate_number', sa.String(length=16), nullable=True))
    op.add_column('currency_detail', sa.Column('plate_position', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_detail', 'plate_position')
    op.drop_column('currency_detail', 'back_plate_number')
    op.drop_column('currency_detail', 'face_plate_number')
    # ### end Alembic commands ###
