"""item_status_history arrived_on

Revision ID: bec2c77439cc
Revises: 90f39bcd06b7
Create Date: 2026-09-09 21:53:10.303385

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bec2c77439cc'
down_revision: str | None = '90f39bcd06b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_status_history', sa.Column('arrived_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_status_history', 'arrived_on')
    # ### end Alembic commands ###
