"""lot lineage: parent item and split marker

Revision ID: fdf22151d022
Revises: a2d3016e44e3
Create Date: 2026-09-06 15:04:03.600560

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models.views import (
    create_views,
    CREATE_VIEWS_WITHOUT_LINEAGE,
    DROP_VIEWS,
)
import sqlalchemy as sa


revision: str = 'fdf22151d022'
down_revision: str | None = 'a2d3016e44e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_item', sa.Column('parent_item_id', sa.Integer(), nullable=True))
    op.add_column('inventory_item', sa.Column('split_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_inventory_item_parent_item_id'), 'inventory_item', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_split_at'), 'inventory_item', ['split_at'], unique=False)
    # Named, because an anonymous constraint cannot be dropped by the
    # downgrade -- it fails with "it has no name".
    op.create_foreign_key(
        'fk_inventory_item_parent', 'inventory_item', 'inventory_item',
        ['parent_item_id'], ['id'], ondelete='RESTRICT',
    )

    # The views now filter on split_at and expose item_code, so they are
    # replaced. A view is not in Base.metadata, so autogenerate cannot see
    # that its definition changed -- the migration that changes the
    # definition has to say so.
    for statement in DROP_VIEWS:
        op.execute(statement)
    # The current view text names columns renamed long after this revision,
    # so it must be rewritten back to what existed here.
    for statement in create_views(renamed_costs=False):
        op.execute(statement)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Views reference the columns dropped below, so they go first.
    for statement in DROP_VIEWS:
        op.execute(statement)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_inventory_item_parent', 'inventory_item', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_item_split_at'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_parent_item_id'), table_name='inventory_item')
    op.drop_column('inventory_item', 'split_at')
    op.drop_column('inventory_item', 'parent_item_id')
    # ### end Alembic commands ###

    # Put the views back as they were before this revision.
    #
    # They cannot be recreated from CREATE_VIEWS: that SQL references
    # split_at and parent_item_id, which the lines above just dropped.
    # Leaving them dropped is not an option either -- the previous revision is
    # supposed to have four views, and a downgrade that quietly removes them
    # leaves a database nothing would flag as broken until something read one.
    for statement in CREATE_VIEWS_WITHOUT_LINEAGE:
        op.execute(statement)
